[package]
authors = ["Andrei Basarab <andy.basarab@gmail.com>"]
name = "cubesat-1-fw-obc"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/cubesat-lab/cubesat-1-sw/"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
# common dependencies
cortex-m = "0.7.7"
cortex-m-rt = "0.7.2"
cortex-m-semihosting = "0.5.0"
embedded-hal = "0.2.7"
fugit = "0.3.6"
panic-halt = "0.2.0"

# "nucleo-f767zi-board" specific dependencies
cc1101-wrapper = { path = "../../../modules/cc1101-wrapper", version = "0.1.0", optional = true}
nucleo-f767zi = { path = "../../../boards/nucleo-f767zi", version = "0.1.0", optional = true}
stm32f7xx-hal = { version = "0.7.0", features = ["stm32f767", "rt"], optional = true}

# "stm32vldiscovery" specific dependencies
stm32f1xx-hal = { version = "0.10.0", features = ["rt", "stm32f100", "medium"], optional = true}


[dev-dependencies]
panic-semihosting = "0.6.0"


[features]
nucleo-f767zi-board = ["cc1101-wrapper", "nucleo-f767zi", "stm32f7xx-hal"]
stm32vldiscovery = ["stm32f1xx-hal"]


[[example]]
name = "button_and_leds"
required-features = ["nucleo-f767zi-board"]

[[example]]
name = "hello_cubesat"
required-features = ["nucleo-f767zi-board"]

[[example]]
name = "hello_stm32vldiscovery"
required-features = ["stm32vldiscovery"]

[[example]]
name = "temp_on_serial"
required-features = ["nucleo-f767zi-board"]

[[example]]
name = "test_cc1101"
required-features = ["nucleo-f767zi-board"]
