[toolchain]
channel = "nightly-2024-09-05"  # This "nightly" build is functional for this project
targets = [
    "thumbv6m-none-eabi",
    "thumbv7em-none-eabi",
    "thumbv7em-none-eabihf",
    "thumbv7m-none-eabi"
]
