# Proposed targets:
#   thumbv6m-none-eabi      Cortex-M0 and Cortex-M0+
#   thumbv7m-none-eabi      Cortex-M3
#   thumbv7em-none-eabi     Cortex-M4 and Cortex-M7 (no FPU)
#   thumbv7em-none-eabihf   Cortex-M4F and Cortex-M7F (with FPU)

[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = "arm-none-eabi-gdb -q -x openocd.gdb"  # Connect to the target using `openocd -f openocd.cfg` after calling `cargo run`
rustflags = ["-C", "link-arg=-Tlink.x"]

[target.thumbv7m-none-eabi]
runner = "qemu-system-arm -cpu cortex-m3 -machine stm32vldiscovery -nographic -semihosting-config enable=on,target=native -kernel"
rustflags = ["-C", "link-arg=-Tlink.x"]