name: Continuous Integration

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    defaults:
      run:
        working-directory: ./firmware/obc/cubesat-1-fw-obc
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: thumbv7em-none-eabihf
        override: true
    - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --verbose
    - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
    - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

