name: Continuous Integration

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        firmware:
          # - adcs
          # - com
          # - eps
          - obc
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: thumbv7em-none-eabihf
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --manifest-path ${{ github.workspace }}/firmware/${{ matrix.firmware }}/cubesat-1-fw-${{ matrix.firmware }}/Cargo.toml --target thumbv7em-none-eabihf --verbose
    # - uses: actions-rs/cargo@v1
    #   with:
    #     command: test
    #     args: --manifest-path ${{ github.workspace }}/firmware/${{ matrix.firmware }}/cubesat-1-fw-${{ matrix.firmware }}/Cargo.toml --target x86_64-unknown-linux-gnu --verbose

